import Head from 'next/head'
import styles from '../styles/Home.module.css'
import canvas from '../src/data.json'
import { Fragment, useState } from 'react'
import Swal from 'sweetalert2'
import Header from '../components/header'
import { useContract, useContractRead } from 'wagmi'
import abi from '../src/abi/abi.json';

export default function Home() {

  //for (let index = 0; index < 100; index++) {
    const contractRead = useContractRead(
      {
        addressOrName: '0xc7a432df0e5364c803e659da7deda317a4b888df',
        contractInterface: abi,
      },
      'getColors',
      {
        onSuccess(data) {
          console.log(index, 'Success', data)
        },
        onError(error) {
          console.log('Error', error)
        },
      },
    )
  //}

  return (
    <div className={styles.container}>
      <Header />

      <Head>
        <title>Fantom Canvas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className='canvas-container'>
          <div className='canvas'>
            {buildCanvas()}
          </div>
        </div>
      </main>
    </div>
  )
}

function click(element) {
  console.log(element);
  Swal.fire('(x:' + element.x + ' y:' + element.y + ') Owned by ' + element.name)
}

function buildCanvas() {
  let lastX = 0;
  let lastY = 0;

  let elements = canvas.items.map(element => {
    /* 
      Color {element.name}
      <br/>
      Name {element.color}
      <br/>
      X: {element.x}
      <br/>
      Y: {element.y}
   */
    let item = (
      <Fragment>
        {element.x < lastX ? (<div className='break'></div>) : ''}
        <div className='item' style={{ backgroundColor: element.color }} onClick={() => click(element)}>

        </div>
      </Fragment>
    )
    lastX = element.x;
    lastY = element.y;

    return item;
  })

  return elements
}